### ISSUE TITLE
Can't run on python3.12.6

### ISSUE THREAD

**Issue by andyfaff** [davidism/gha-update#8] opened 2024-09-20 09:56 UTC
I'm trying to run `gha-update` over the scipy repository. I navigate to the root of the repo and run the script, but it fails with the following stacktrace (python3.12.6):

```
(dev3) 192-168-1-105:scipy andrew$ gha-update
Traceback (most recent call last):
  File "/Users/andrew/miniforge3/envs/dev3/bin/gha-update", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/site-packages/gha_update/_cli.py", line 21, in cli
    asyncio.run(update_workflows(config))
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/site-packages/gha_update/_core.py", line 44, in update_workflows
    versions = await get_versions(actions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/site-packages/gha_update/_core.py", line 98, in get_versions
    out[name] = highest_version(task.result().json())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/dev3/lib/python3.12/site-packages/gha_update/_core.py", line 104, in highest_version
    items: dict[str, str] = {t["name"]: t["commit"]["sha"] for t in tags}
                             ~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by davidism** [comment] 2024-09-20 11:46
Duplicate of https://github.com/davidism/gha-update/issues/1

**Closed as completed by davidism** 2024-09-20 11:46 UTC

**Comment by andyfaff** [comment] 2024-09-20 11:50
Sorry for the noise. I looked through the issues but nothing seemed like my report. Is there a workaround?

**Comment by davidism** [comment] 2024-09-20 12:28
Submit a fix for the issue ;-)

**Comment by davidism** [comment] 2024-09-20 12:31
Until the issue is fixed, you can manually rename whatever action was moved to its new name.

**Comment by andyfaff** [comment] 2024-09-20 13:00
Do you mean that one of the actions we use in our yaml files is now called something else?

**Comment by davidism** [comment] 2025-07-14 03:19
0.2.0 is now available!
