### ISSUE TITLE
Github may return response codes indicating a redirect

### ISSUE THREAD

**Issue by AndEsterson** [davidism/gha-update#10] opened 2024-12-03 11:55 UTC
Github will sometimes give 301,302,307 response codes, which indicate redirects https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#follow-redirects

gha-update doesn't expect this and so will error with

```
Traceback (most recent call last):
  File "/Users/andrew.esterson/code/github/PyBaMM/pybamm/bin/gha-update", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/andrew.esterson/code/github/PyBaMM/pybamm/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew.esterson/code/github/PyBaMM/pybamm/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/andrew.esterson/code/github/PyBaMM/pybamm/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew.esterson/code/github/PyBaMM/pybamm/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew.esterson/code/github/gha-update/src/gha_update/_cli.py", line 21, in cli
    asyncio.run(update_workflows(config))
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/andrew.esterson/code/github/gha-update/src/gha_update/_core.py", line 44, in update_workflows
    versions = await get_versions(actions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew.esterson/code/github/gha-update/src/gha_update/_core.py", line 98, in get_versions
    out[name] = highest_version(task.result().json())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew.esterson/code/github/gha-update/src/gha_update/_core.py", line 104, in highest_version
    items: dict[str, str] = {t["name"]: t["commit"]["sha"] for t in tags}
                             ~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by davidism** [comment] 2024-12-03 14:07
Duplicate of #1

**Closed as completed by davidism** 2024-12-03 14:07 UTC

**Comment by davidism** [comment] 2025-07-14 03:19
0.2.0 is now available!
